//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonDirectory.Application.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PersonDirectory.Application.Shared.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქალაქი არ მოიძებნა.
        /// </summary>
        public static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ფაილი არ არსებობს.
        /// </summary>
        public static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური ასაკი.
        /// </summary>
        public static string InvalidAge {
            get {
                return ResourceManager.GetString("InvalidAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური ფაილის სახელი.
        /// </summary>
        public static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური სახელი.
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური სქესი.
        /// </summary>
        public static string InvalidGender {
            get {
                return ResourceManager.GetString("InvalidGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური ID.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური გვარი.
        /// </summary>
        public static string InvalidLastName {
            get {
                return ResourceManager.GetString("InvalidLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური პერსონა.
        /// </summary>
        public static string InvalidPerson {
            get {
                return ResourceManager.GetString("InvalidPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური პირადი ნომერი.
        /// </summary>
        public static string InvalidPersonalNumber {
            get {
                return ResourceManager.GetString("InvalidPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური ტელეფონის ნომერი.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არავალიდური კავშირის ტიპი.
        /// </summary>
        public static string InvalidRelationshipType {
            get {
                return ResourceManager.GetString("InvalidRelationshipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პერსონა და დაკავშირებული პერსონა იგივეა.
        /// </summary>
        public static string PersonAndRelatedPersonAreSame {
            get {
                return ResourceManager.GetString("PersonAndRelatedPersonAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პერსონა არ მოიძებნა.
        /// </summary>
        public static string PersonNotFound {
            get {
                return ResourceManager.GetString("PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დაკავშირებული პერსონა არ მოიძებნა.
        /// </summary>
        public static string RelatedPersonNotFound {
            get {
                return ResourceManager.GetString("RelatedPersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კავშირი უკვე არსებობს.
        /// </summary>
        public static string RelationshipAlreadyExists {
            get {
                return ResourceManager.GetString("RelationshipAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კავშირი არ არსებობს.
        /// </summary>
        public static string RelationshipDoesNotExist {
            get {
                return ResourceManager.GetString("RelationshipDoesNotExist", resourceCulture);
            }
        }
    }
}
